import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { AnimatePresence, motion, useScroll, useSpring } from 'framer-motion'
import Lenis from 'lenis'
import { FiArrowDown, FiArrowUp, FiArrowUpRight, FiGithub, FiLinkedin, FiMail, FiMenu, FiX } from 'react-icons/fi'
import { projects, roles, technologies, timeline } from './data/content'
import { SectionHeading } from './components/SectionHeading'
import { MagneticButton } from './components/MagneticButton'
import { OrbitalScene } from './components/OrbitalScene'
import { useReducedMotion } from './hooks/useReducedMotion'
import './styles/global.css'

function Loader({ done }: { done: () => void }) { const [n, setN] = useState(0); useEffect(() => { const id = window.setInterval(() => setN(v => { if(v >= 100) { clearInterval(id); setTimeout(done, 250); return 100 }; return Math.min(100, v + 4) }), 24); return () => clearInterval(id) }, [done]); return <motion.div className="loader" exit={{ opacity: 0 }} transition={{ duration: .55 }}><div><span className="loader-mark">VK</span><p>INITIALIZING EXPERIENCE</p><strong>{String(n).padStart(3, '0')}</strong></div></motion.div> }
function App() {
 const [loaded, setLoaded] = useState(false), [menu, setMenu] = useState(false), [role, setRole] = useState(0)
 const reduced = useReducedMotion(); const { scrollYProgress } = useScroll(); const scaleX = useSpring(scrollYProgress, { stiffness: 100, damping: 30 })
 useEffect(() => { const lenis = new Lenis({ lerp: .09 }); let frame: number; const raf = (time: number) => { lenis.raf(time); frame = requestAnimationFrame(raf) }; frame = requestAnimationFrame(raf); return () => { cancelAnimationFrame(frame); lenis.destroy() } }, [])
 useEffect(() => { if (reduced) return; const id = setInterval(() => setRole(i => (i + 1) % roles.length), 2300); return () => clearInterval(id) }, [reduced])
 return <><AnimatePresence>{!loaded && <Loader done={() => setLoaded(true)} />}</AnimatePresence><motion.div className="progress" style={{ scaleX }} />
 <header className="nav"><a href="#top" className="brand" aria-label="Varshikan K home">VK<span>.</span></a><nav className={menu ? 'open' : ''}>{['Work', 'About', 'Journey', 'Contact'].map(x => <a onClick={() => setMenu(false)} href={`#${x.toLowerCase()}`} key={x}>{x}</a>)}</nav><a className="nav-contact" href="#contact">Let’s talk <FiArrowUpRight /></a><button className="menu" onClick={() => setMenu(!menu)} aria-label="Toggle menu">{menu ? <FiX /> : <FiMenu />}</button></header>
 <main id="top">
 <section className="hero"><div className="ambient a"/><div className="ambient b"/><div className="hero-copy"><motion.p className="eyebrow" initial={{ opacity: 0 }} animate={{ opacity: loaded ? 1 : 0 }}>PRE-FINAL YEAR · VIT CHENNAI</motion.p><h1><span>I engineer</span><span className="italic">intelligent</span><span>products.</span></h1><div className="role-line"><span>Currently becoming</span><AnimatePresence mode="wait"><motion.b key={roles[role]} initial={{ y: 18, opacity: 0 }} animate={{ y: 0, opacity: 1 }} exit={{ y: -18, opacity: 0 }}>{roles[role]}</motion.b></AnimatePresence></div><p className="hero-intro">From idea to production, I design software systems that make complex problems feel clear, useful, and human.</p><div className="actions"><MagneticButton href="#work">Explore selected work</MagneticButton><MagneticButton href="#contact" variant="outline">Start a conversation</MagneticButton></div></div><OrbitalScene /><a href="#about" className="scroll-cue">SCROLL TO DISCOVER <FiArrowDown /></a></section>
 <section id="about" className="about"><SectionHeading eyebrow="01 / INTENT" title="Built from curiosity. Guided by precision."/><div className="about-grid"><p className="statement">I’m Varshikan — an AI & ML student who sees engineering as a craft: observe closely, reduce the noise, and build what genuinely moves people forward.</p><div><p>Currently pursuing my B.Tech at VIT Chennai, I’m drawn to the intersection of intelligent systems, full-stack product thinking, and relentless iteration.</p><p>The goal is not to collect technologies. It’s to use the right ones to make an impact.</p><a className="text-link" href="#journey">Read my journey <FiArrowUpRight /></a></div></div></section>
 <section className="principles"><span className="eyebrow">02 / OPERATING SYSTEM</span><div className="principle-list">{['Build products, not prototypes.', 'AI should solve meaningful problems.', 'Precision is a form of care.', 'Simple solutions earn their place.'].map((p, i) => <motion.div initial={{ opacity: 0, x: -24 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} transition={{ delay: i * .08 }} key={p}><b>0{i + 1}</b><h3>{p}</h3><i>↗</i></motion.div>)}</div></section>
 <section id="work" className="work"><SectionHeading eyebrow="03 / SELECTED WORK" title="Software with a reason to exist." copy="A few systems built around real constraints — clarity, collaboration, and useful intelligence."/><div className="project-list">{projects.map((p, i) => <motion.article className="project" key={p.name} initial={{ opacity: 0, y: 35 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .2 }} transition={{ delay: i * .06 }}><div className={`project-visual visual-${i}`}><span>{p.number}</span><div className="visual-lines"/><small>{p.tag}</small></div><div className="project-copy"><span className="eyebrow">{p.tag}</span><h3>{p.name}</h3><p>{p.summary}</p><dl><div><dt>Challenge</dt><dd>{p.problem}</dd></div><div><dt>Outcome</dt><dd>{p.outcome}</dd></div></dl><div className="stack">{p.stack.map(s => <span key={s}>{s}</span>)}</div><a className="text-link" href={p.link}>View case study <FiArrowUpRight /></a></div></motion.article>)}</div></section>
 <section className="research"><div><span className="eyebrow">04 / ACTIVE EXPLORATION</span><h2>Finding the<br/><em>fastest line.</em></h2><p>Racing Line Optimization is an ongoing research-led engineering effort at the overlap of machine learning, simulation, and vehicle dynamics.</p><a className="text-link" href="#contact">Follow the work <FiArrowUpRight /></a></div><div className="track" aria-label="Abstract racing line visualization"><span className="active-chip">● ACTIVE DEVELOPMENT</span><svg viewBox="0 0 500 500" role="img"><path d="M94 105C233-8 449 58 379 181c-52 92-211 44-194 141 14 81 211 78 205-66"/><path className="racing" d="M94 105C233-8 449 58 379 181c-52 92-211 44-194 141 14 81 211 78 205-66"/></svg><div className="track-stat"><b>IN PROGRESS</b><span>SIMULATION / OPTIMIZATION</span></div></div></section>
 <section className="tech"><SectionHeading eyebrow="05 / TECH UNIVERSE" title="Tools are only as valuable as the systems they help create."/><div className="constellation">{technologies.map((t, i) => <motion.button key={t} whileHover={{ y: -5, scale: 1.04 }} className={`node n${i % 5}`}><i/><span>{t}</span></motion.button>)}</div></section>
 <section id="journey" className="journey"><SectionHeading eyebrow="06 / TRAJECTORY" title="A journey in motion."/><div className="timeline">{timeline.map(([year, title, text], i) => <motion.article key={title} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}><span>{year}</span><div className="timeline-dot"/><h3>{title}</h3><p>{text}</p><b>0{i + 1}</b></motion.article>)}</div></section>
 <section id="contact" className="contact"><span className="eyebrow">07 / MAKE CONTACT</span><h2>Let’s build something<br/><em>with intent.</em></h2><p>Open to thoughtful conversations about software, AI, research, and the next difficult thing worth solving.</p><a href="mailto:varshikan07@gmail.com" className="contact-mail">varshikan07@gmail.com <FiArrowUpRight /></a><div className="socials"><a href="https://github.com/Varshikan07" aria-label="GitHub"><FiGithub /></a><a href="https://www.linkedin.com/in/varshikan" aria-label="LinkedIn"><FiLinkedin /></a><a href="mailto:varshikan07@gmail.com" aria-label="Email"><FiMail /></a></div></section>
 </main><footer><span>© 2026 VARSHIKAN K</span><span>DESIGNED WITH CURIOSITY · BUILT WITH PRECISION</span><a href="#top" aria-label="Back to top">BACK TO TOP <FiArrowUp /></a></footer></>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>)
